version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis

  portainer:
    image: portainer/portainer-ce

  catalog.webapi:
    image: ${DOCKER_REGISTRY-}catalogwebapi
    build:
      context: .
      dockerfile: Catalog/Catalog.WebApi/Dockerfile
      
  basket.webapi:
    image: ${DOCKER_REGISTRY-}basketwebapi
    build:
      context: .
      dockerfile: Basket/Basket.WebApi/Dockerfile

volumes:
  mongo_data: 
  portainer_data:
