version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  catalog.webapi:
    image: ${DOCKER_REGISTRY-}catalogwebapi
    build:
      context: .
      dockerfile: Catalog/Catalog.WebApi/Dockerfile
      
  basket.webapi:
    image: ${DOCKER_REGISTRY-}basketwebapi
    build:
      context: .
      dockerfile: Basket/Basket.WebApi/Dockerfile

  discount.webapi:
    image: ${DOCKER_REGISTRY-}discountwebapi
    build:
      context: .
      dockerfile: Discount/Discount.WebApi/Dockerfile

volumes:
  mongo_data: 
  portainer_data:
  postgres_data:
  pgadmin_data:

